version: "3.3"
services:
  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=example
    ports:
      - 5432:5432
  alembic:
    build:
      context: .
      dockerfile: alembic.dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db
      - alembic
    ports:
      - 8000:8000

volumes:
  db-data:

