version: "3.3"
services:
  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=example
    ports:
      - 5432:5432
  app:
    build:
      context: .
    env_file:
      - ./app/.env
    environment:
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - 8000:8000

volumes:
  db-data:

