"""Add new column

Revision ID: a3effb6c4b1c
Revises: 1f7023643ad8
Create Date: 2021-08-17 23:37:57.291851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3effb6c4b1c'
down_revision = '1f7023643ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('received_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'received_at')
    # ### end Alembic commands ###
