"""Rename column

Revision ID: 542c54c95641
Revises: dc625d578eb8
Create Date: 2021-08-19 10:22:05.432468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '542c54c95641'
down_revision = 'dc625d578eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('displacement_speed', sa.Float(), nullable=True))
    op.drop_column('positions', 'calculated_speed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('calculated_speed', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('positions', 'displacement_speed')
    # ### end Alembic commands ###
